name: Build and Test

on:
  push:
    branches:
      - cacarlt/get_build_pipeline_working
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.6'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Build the binary
        run: |
          cd src/transcode_handler
          go mod download
          go build -o transcode-handler main.go
          ls -l transcode-handler

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: transcode-handler-binary
          path: src/transcode_handler/transcode-handler