name: transcode_handler_build

permissions:
  contents: write

on:
  push:
    branches:
      -  cacarlt/get_build_pipeline_working

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important to fetch all tags

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.6'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Build the binary
        run: |
          cd src/transcode_handler
          go mod download
          go build -o transcode-handler main.go
          ls -l transcode-handler

      - name: Get latest tag
        id: get-latest-tag-binary
        uses: actions-ecosystem/action-get-latest-tag@v1

      - name: Bump version
        id: bump-version
        uses: actions-ecosystem/action-bump-semver@v1
        with:
          current_version: ${{ steps.get-latest-tag-binary.outputs.tag }}
          level: patch  # Can be major, minor, or patch

      # Only create a new tag on pushes to main branch (not PRs)
      - name: Create Tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-version.outputs.new_version }}
          message: "Release ${{ steps.bump-version.outputs.new_version }}"
        
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: transcode-handler-binary
          path: src/transcode_handler/transcode-handler

  build-docker-server:
    needs: build-binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: transcode-handler-binary
          path: .

      - name: Get latest tag
        id: get-latest-tag-docker
        uses: actions-ecosystem/action-get-latest-tag@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.server
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/transcode-handler/server:latest
            ghcr.io/${{ github.repository_owner }}/transcode-handler/server:${{ steps.get-latest-tag-docker.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/transcode-handler/server:${{ github.sha }}