name: transcode_handler_build
on:
  push:
    branches:
      -  cacarlt/get_build_pipeline_working

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important to fetch all tags

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.6'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('src/transcoder/go.sum') }}

      - name: Build the binary
        run: |
          cd src/transcode_handler
          go mod download
          go build -o transcode-handler main.go
          ls -l transcode-handler

      - name: Get latest tag
        id: get-latest-tag-binary
        uses: actions-ecosystem/action-get-latest-tag@v1

      - name: Bump version
        id: bump-version
        uses: actions-ecosystem/action-bump-semver@v1
        with:
          current_version: ${{ steps.get-latest-tag-binary.outputs.tag }}
          level: patch  # Can be major, minor, or patch

      # Only create a new tag on pushes to main branch (not PRs)
      - name: Create Tag
        if: github.event_name == 'pull_request'
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-version.outputs.new_version }}
          message: "Release ${{ steps.bump-version.outputs.new_version }}"
        
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: transcode-handler-binary
          path: src/transcode_handler/transcode-handler

  build-docker-server:
    needs: build-binary
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    env:
      HAS_DOCKER_SECRETS: ${{ secrets.D_USER != '' && secrets.D_PAT != '' }}
      IMAGE_NAME: ${{ github.repository }}/server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: transcode-handler-binary
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.1.0
        if: env.HAS_DOCKER_SECRETS
        with:
          username: ${{ secrets.D_USER }}
          password: ${{ secrets.D_PAT }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ${{ github.repository_owner }}/transcode-handler-server
            ghcr.io/${{ github.repository_owner }}/transcode-handler-server
          labels: |
            org.opencontainers.image.authors=Cameron Carlton
            org.opencontainers.image.source="https://github.com/camcast3/transcode_handler"
            org.opencontainers.image.description="A web server for queuing video transcoding jobs"
            org.opencontainers.image.licenses="MIT"

      - name: Build and push
        uses: docker/build-push-action@v6.13.0
        if: github.actor == github.repository_owner 
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          pull: true
          labels: ${{ steps.meta.outputs.labels }}